### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ave-Wat** [Ave-Wat/Ave-Wat.github.io#6]
- [ ] Create sticky navbar
- [ ] create search bar for projects (by language, topic, name, etc)
- [ ] create landing page for each project
